### PR TITLE
[feature] Updated unit & e2e tests

### PR DESCRIPTION
**Pull request by alex-deaconu**

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Finally the build is fixed. Added unit/e2e tests, fixed some issues with the package.json references, and added confirm instance controller files. Still thinking of how to move those to the components repo..

@rodrigopavezi please review. Thanks!

**Comment by rodrigopavezi** [comment]
@alex-deaconu nice, I guess we can move the commonheaderPage and googleAuthPage e2e classes to the widget-tests as they are pretty common. Ah, one thing that I've been noticing is that we should start to add ids to the web elements so it becomes easier to reference it on the e2e tests. For checking that a common-header sign up shows up I used the element with a ccs class .modal-dialog. But that is to generic. The best would be to change CH but I left it for another time. cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi I definitely agree re: moving all those common classes. Is that something you can take care of?

Also re: css selectors, whenever the tests run there's a lot of duplicate element warnings. I wonder if there's something we can do about those as well?

Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu yea, the warning is due to the spinner. There is a time that we have two in the same DOM without ids with the same class .spinner-backdrop. So I use the css class to get the element for waiting it to go away so other elements can be clicked.

We can fix that adding an id for the CH spinner element. cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi got it, thanks for the confirmation.

**Pull request merged**
