### PR TITLE
[feature] Playlist Item delete and move functionality [stage-2]

### PR DESCRIPTION
**Pull request by alex-deaconu**
Empty playlist state
Created separate playlistFactory for playlist functionality

Updated common-style branch

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi please review. Thanks.

**Comment by rodrigopavezi** [comment]
LG :+1: I wonder if we should have e2e tests for that.

**Comment by alex-deaconu** [comment]
@rodrigopavezi yes it would be nice. Will add. Thanks.

**Comment by alex-deaconu** [comment]
Merging this, will open another PR for the e2e tests. Thanks!

**Pull request merged**
