### PR TITLE
fix list [stage-1]

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@ezequielc @alex-deaconu fix for schedules playlist items list

### CODE REVIEW

**Comment by ezequielc** [comment]
@ghislaineguerin looks good! :+1:

**Comment by alex-deaconu** [comment]
@ghislaineguerin no matter how many playlist items I have, I always get a horizontal scrollbar in this version: http://screencast.com/t/tscRC1ISlFN. Thanks.

**Comment by ghislaineguerin** [comment]
@alex-deaconu when is that happening?

**Comment by alex-deaconu** [comment]
@ghislaineguerin try it in this Schedule: https://schedules-stage-1.risevision.com/#/schedule/details/bc33890b-15ea-42b1-853f-26b93cc7c71d?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443. I guess it only happens when the URL field is super long. Thanks.

**Comment by ghislaineguerin** [comment]
@alex-deaconu seems like I have to add my responsive text fix to all lists on displays and schedules. Can we merge this and I'll open a card for that?

**Comment by alex-deaconu** [comment]
@ghislaineguerin that's fine. Sorry thought this was related. New card sounds good.

:+1:  for this PR. Thanks.

**Pull request merged**
