### PR TITLE
Augmented e2e test scenarios in one single test suite.

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@alex-deaconu following your idea, I've got a single test suite which runs all the scenarios and write to the same report file. e.g. https://circleci.com/gh/Rise-Vision/schedules-app/295

Please review.
@ezequielc FYI.
cheers

### CODE REVIEW

**Comment by ezequielc** [comment]
@rodrigopavezi Thanks. Quick question: if I need to run a single scenario, I can just comment the others in `e2e/test-suite.scenarios.js`, right?

**Comment by alex-deaconu** [comment]
@rodrigopavezi looks good.

I think however you should modify the e2e task in `gulpfile.js` to only test that one file (`test-suite.scenarios.js`). I believe it is also running the tests from the `cases/` folder (http://screencast.com/t/Gyifa5vkYv). 

Also, I can't seem to find any test reports in CCI. We're saving a file in JUnit XML format, but is it going to the right directory?

Thanks.

**Comment by rodrigopavezi** [comment]
@ezequielc actually we can still use the TEST_FILES variable to run a single test.

@alex-deaconu good catch. I will rename the case files so they don't contain scenarios token. Re. the CCI report folder the change is on this PR https://github.com/Rise-Vision/schedules-app/pull/52. Once it is merged it should work. cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi looks good :+1: . 

Sorry missed the other PR thought I had reviewed it. Thanks.

**Pull request merged**
