### PR TITLE
[chore] Refactoring Playlist and Playlist Item UI [stage-2]

### PR DESCRIPTION
**Pull request by alex-deaconu**
No more expanding list items; Items are managed via modal dialog
Adding an url item opens the Manage dialog
Adding a presentation opens the selector and once selected
the Manage dialog is shown
Delete button moved & style updated

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi please review. Thanks!

**Comment by alex-deaconu** [comment]
fixed failing e2e test.

**Comment by rodrigopavezi** [comment]
@alex-deaconu LG :+1:. Just a small thing. I think there should be a hand pointer when selecting a presentation. @ghislaineguerin FYI. cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi I agree. Noticed that as well. I think there's something changed in the list styling so it's not showing up. However, we have a PR open for styling improvements #13. Will check if it's fixed there. @ghislaineguerin FYI. Thanks.

**Pull request merged**
