### PR TITLE
Implemented load of presentation list.

### PR DESCRIPTION
**Pull request by rodrigopavezi**
[stage-0]

@alex-deaconu please review. I had to disable a e2e test for checking if the presentations are loaded. It is working fine on my local but not on cci. I will troubleshoot it tomorrow. cheers

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi looks good. However, do you think you can split up the Presentation list logic (filter, spinner, load, search etc) from the `addPresentationModal` controller? Just put it in a separate controller, and use a `$broadcast` message to send the selected item to the original controller. 

I think the presentation selector list should be a re-useable component and this would be a first step. Thoughts? 

Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu makes total sense. I will do that. cheers

**Comment by rodrigopavezi** [comment]
@alex-deaconu I have made the changes and fixed e2e test. It was failing because the Jenkins user did not have a presentation. Please review. cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi one question re: e2e tests being disabled. Otherwise LG :+1: . Thanks!

**Pull request merged**
