### PR TITLE
Added browser-sync

### PR DESCRIPTION
**Pull request by rodrigopavezi**
Upgraded gulp libs
Cleaned up gulp file

@alex-deaconu please review. cheers

It is deployed to stage-0

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavez are the spacing changes from the new jsbeautify version?

**Comment by alex-deaconu** [comment]
Also, do you mind if we add `open: false` to the browser-sync options? I find it annoying when it opens my browser automatically upon running the task? Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu yeap, I think the indentation is due to the new version of the jsbeautify. Re. the auto open. I like this. It is an awesome feature. If that annoys you I can change of course. cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi okay, just leave as is. :+1: . Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu no worries, changed. For me I don't mind. Actually, if I have to run gulp dev more than once it won't open other browsers. I think it's a valid point. cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi that was my concern. Thanks for updating!

**Comment by rodrigopavezi** [comment]
@alex-deaconu thanks for bringing that up :-)

**Pull request merged**
