### PR TITLE
[feature] Added playlist and playlist item directives

### PR DESCRIPTION
**Pull request by alex-deaconu**
Updated Add/Edit url/presentation item logic

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi please review. Thanks!

**Comment by rodrigopavezi** [comment]
@alex-deaconu I think you've missed the [stage-2] tag. cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi fixed. Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu should the error the image happen?
screen shot 2015-06-24 at 5 28 21 pm
cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi good catch. This is actually fixed in the next PR, but I updated this one as well. Thanks!

**Comment by rodrigopavezi** [comment]
@alex-deaconu awesome! cheers :+1:

**Pull request merged**
