### PR TITLE
Check Content Publisher role

### PR DESCRIPTION
**Pull request by alex-deaconu**
Use require-role directive to remove actions if not allowed

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu I think we could hide Add Schedule button, and if it is not to complicated, hide Add Playlist Item and item actions. Cheers

**Comment by alex-deaconu** [comment]
@ezequielc now removing the Add Schedule buttons from the Add and Manage pages.

Re: other actions, I can remove but I feel it would be inconsistent with the behaviour of the other Editor. Thoughts? 

Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Yes, I think you are right. :+1:

**Pull request merged**
